version: '3.8'

services:
  laravel-app:
    image: api-filmes-laravel-app
    build:
      context: .
      dockerfile: Dockerfile  # Especifica o Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - laravel-mysql
    ports:
      - "9000:9000"

  laravel-webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Altere o arquivo nginx.conf se necessário
    networks:
      - app-network
    depends_on:
      - laravel-app
    ports:
      - "8081:80"

  laravel-mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: curso_api_filmes
    volumes:
      - laravel-mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  laravel-mysql-data:
    driver: local
